# -----------------------------------------------------------------------------
# Copyright Siemens AG, 2016-2017.
# Copyright Bosch Software Innovations GmbH, 2017.
# Part of the SW360 Portal Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# initial author: maximilian.huber@tngtech.com
# -----------------------------------------------------------------------------

sudo: required
dist: xenial
language: java
jdk: openjdk11
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker

cache:
  apt: true
  directories:
    - $HOME/.m2
    - /tmp/

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y couchdb
  - sudo service couchdb restart
  - ./scripts/install-thrift.sh --no-cleanup

env:
  MVN_ARGS="package"
install:
  mvn dependency:resolve || true
script:
  mvn --fail-at-end $MVN_ARGS

matrix:
  include:
    - name: mvn package
      env: MVN_ARGS="package"
    - name: mvn validate
      env: MVN_ARGS="validate"
      before_install:
    - name: mvn dependency:analyze
      env: MVN_ARGS="dependency:analyze -DfailOnWarning"
      install: mvn package -DskipTests
    - name: check for license headers
      before_install: true
      install: true
      script: .travis/testForLicenseHeaders.sh
    # the following job sadly runs into timeout
    # - name: test docker install file
    #   before_install: true
    #   install: true
    #   script: scripts/compileWithDocker.sh
  allow_failures:
    - name: mvn dependency:analyze
